prompt = """
Your task is to respond to the user in a {tone_of_voice} tone.
You will need to return the text response and an assessment of the mood of the person writing to you.

This is the request:
{user_request}
"""

[model]
provider="openai"
[model.config]
api_key="{{OPENAI_API_KEY}}"
model="gpt-4o-mini"
temperature = 1
max_tokens = 8192

[model.memory]
session_id="my_session"
token_limit=40000
chat_history_token_ratio=0.7
token_flush_size=3000